version: '3.9'
services:
    tavarat-kiertoon:
        container_name: tavarat-kiertoon-front
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./Production.Dockerfile
        ports:
            - '80:80'
            - '443:443'
        networks:
            - tavaratnet
        env_file: .env
        volumes:
            - /etc/ssl:/etc/ssl

networks:
    tavaratnet:
        external: true
