version: '3.9'
services:
    tavarat-kiertoon:
        container_name: tavarat-kiertoon-front
        restart: unless-stopped
        build: .
        ports:
            - '80:80'
            - '443:443'
        networks:
            - tavaratnet

networks:
    tavaratnet:
        driver: bridge
