name: 'Tests: tests'

on:
    pull_request:
        branches: [develop]

env:
    GITHUB_PR_NUMBER: ${{github.event.pull_request.number}}

jobs:
    tests_ci:
        name: Run git-front tests
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: install dependencies
              run: npm ci
            - name: build
              run: npm run build
            - name: install playwright browsers
              run: npx playwright install --with-deps
            - name: run tests
              run: npx playwright test tests/git/
